/* Deutsch für Ingenieure – content pack v2
   VOCAB: [deck, German, English, German example, English example] */
const VOCAB=[
["Arbeit","die Bewerbung, -en","application","Ich schicke meine Bewerbung heute ab.","I'm sending off my application today."],
["Arbeit","der Lebenslauf, ¨e","CV, résumé","Mein Lebenslauf ist auf dem neuesten Stand.","My CV is up to date."],
["Arbeit","das Anschreiben, -","cover letter","Im Anschreiben erkläre ich meine Motivation.","In the cover letter I explain my motivation."],
["Arbeit","der Werkstudent, -en","working student","Ich suche eine Stelle als Werkstudent in der Entwicklung.","I'm looking for a working-student position in development."],
["Arbeit","das Praktikum, Praktika","internship","Mein Praktikum dauert sechs Monate.","My internship lasts six months."],
["Arbeit","die Abschlussarbeit, -en","thesis","Ich möchte meine Abschlussarbeit in einem Unternehmen schreiben.","I'd like to write my thesis at a company."],
["Arbeit","das Vorstellungsgespräch, -e","job interview","Nächste Woche habe ich ein Vorstellungsgespräch.","I have a job interview next week."],
["Arbeit","die Stelle, -n","position, job","Die Stelle ist ab sofort zu besetzen.","The position is to be filled immediately."],
["Arbeit","die Kenntnisse (Pl.)","skills, knowledge","Ich habe gute CAD-Kenntnisse.","I have good CAD skills."],
["Arbeit","die Erfahrung, -en","experience","Ich habe Erfahrung mit FEM-Simulationen.","I have experience with FEM simulations."],
["Arbeit","der Vorgesetzte, -n","supervisor, boss","Mein Vorgesetzter hat die Aufgabe verteilt.","My supervisor assigned the task."],
["Arbeit","die Besprechung, -en","meeting","Die Besprechung beginnt um neun Uhr.","The meeting starts at nine o'clock."],
["Arbeit","der Termin, -e","appointment, deadline","Wir müssen den Termin einhalten.","We have to meet the deadline."],
["Arbeit","die Frist, -en","deadline (time limit)","Die Frist läuft am Freitag ab.","The deadline expires on Friday."],
["Arbeit","zuständig sein für","to be responsible for","Wer ist für die Qualitätsprüfung zuständig?","Who is responsible for quality inspection?"],
["Arbeit","die Aufgabe, -n","task","Meine Aufgabe ist die Auswertung der Messdaten.","My task is evaluating the measurement data."],
["Arbeit","der Arbeitsvertrag, ¨e","employment contract","Ich habe den Arbeitsvertrag gestern unterschrieben.","I signed the employment contract yesterday."],
["Arbeit","das Gehalt, ¨er","salary","Das Gehalt wird am Monatsende überwiesen.","The salary is transferred at the end of the month."],
["Arbeit","sich bewerben um","to apply for","Ich bewerbe mich um eine Werkstudentenstelle.","I'm applying for a working-student position."],
["Arbeit","die Rückmeldung, -en","feedback, reply","Ich warte noch auf eine Rückmeldung.","I'm still waiting for a reply."],
["Arbeit","der Ansprechpartner, -","contact person","Wer ist mein Ansprechpartner für dieses Thema?","Who is my contact person for this topic?"],
["Arbeit","die Unterlagen (Pl.)","documents","Bitte schicken Sie uns Ihre vollständigen Unterlagen.","Please send us your complete documents."],
["Arbeit","sich einarbeiten","to get up to speed","In den ersten Wochen arbeite ich mich in das Thema ein.","In the first weeks I'll get up to speed on the topic."],
["Arbeit","verschieben","to postpone","Können wir den Termin auf Montag verschieben?","Can we postpone the appointment to Monday?"],
["Technik","der Werkstoff, -e","material","Stahl ist ein häufig verwendeter Werkstoff.","Steel is a commonly used material."],
["Technik","die Festigkeit, -en","strength","Die Festigkeit des Materials wird im Zugversuch geprüft.","The strength of the material is tested in a tensile test."],
["Technik","die Belastung, -en","load","Das Bauteil hält dieser Belastung nicht stand.","The component cannot withstand this load."],
["Technik","die Spannung, -en","stress; voltage","Die maximale Spannung liegt im Bereich der Kerbe.","The maximum stress is in the area of the notch."],
["Technik","die Verformung, -en","deformation","Die Verformung bleibt unter einem Millimeter.","The deformation stays below one millimetre."],
["Technik","der Wirkungsgrad, -e","efficiency","Der Wirkungsgrad des Getriebes liegt bei 95 Prozent.","The efficiency of the gearbox is around 95 percent."],
["Technik","die Zeichnung, -en","drawing","Die Maße stehen in der technischen Zeichnung.","The dimensions are in the technical drawing."],
["Technik","das Bauteil, -e","component, part","Das Bauteil wird aus Aluminium gefertigt.","The component is made of aluminium."],
["Technik","die Baugruppe, -n","assembly","Die Baugruppe besteht aus zehn Einzelteilen.","The assembly consists of ten individual parts."],
["Technik","die Toleranz, -en","tolerance","Die Toleranz beträgt plus minus 0,1 Millimeter.","The tolerance is plus/minus 0.1 millimetres."],
["Technik","die Fertigung","manufacturing, production","Die Fertigung läuft im Dreischichtbetrieb.","Production runs in three shifts."],
["Technik","das Fertigungsverfahren, -","manufacturing process","Welches Fertigungsverfahren eignet sich für diese Serie?","Which manufacturing process is suitable for this series?"],
["Technik","fräsen","to mill","Die Nut wird auf der CNC-Maschine gefräst.","The groove is milled on the CNC machine."],
["Technik","drehen","to turn (lathe)","Die Welle wird auf der Drehmaschine gedreht.","The shaft is turned on the lathe."],
["Technik","schweißen","to weld","Die beiden Bleche werden miteinander verschweißt.","The two metal sheets are welded together."],
["Technik","die Schraube, -n","screw, bolt","Die Schrauben müssen mit 20 Newtonmeter angezogen werden.","The bolts must be tightened to 20 newton-metres."],
["Technik","die Welle, -n","shaft","Die Welle überträgt das Drehmoment vom Motor auf das Zahnrad.","The shaft transmits the torque from the motor to the gear."],
["Technik","das Lager, -","bearing","Das Lager muss regelmäßig geschmiert werden.","The bearing must be lubricated regularly."],
["Technik","das Zahnrad, ¨er","gear","Das Zahnrad hat vierzig Zähne.","The gear has forty teeth."],
["Technik","das Drehmoment, -e","torque","Das maximale Drehmoment beträgt 200 Newtonmeter.","The maximum torque is 200 newton-metres."],
["Technik","die Konstruktion, -en","design, construction","Die Konstruktion muss leichter werden.","The design has to become lighter."],
["Technik","konstruieren","to design (engineer)","Wir konstruieren ein neues Gehäuse.","We are designing a new housing."],
["Technik","die Berechnung, -en","calculation","Die Berechnung basiert auf der Finite-Elemente-Methode.","The calculation is based on the finite element method."],
["Technik","das Netz, -e","mesh (FEM); net","Das Netz muss im Bereich der Kerbe feiner werden.","The mesh needs to be finer around the notch."],
["Technik","der Prüfstand, ¨e","test bench","Der Motor läuft seit Stunden auf dem Prüfstand.","The engine has been running on the test bench for hours."],
["Technik","die Qualitätssicherung","quality assurance","Die Qualitätssicherung prüft jedes zehnte Teil.","Quality assurance inspects every tenth part."],
["Technik","das Lastenheft, -e","requirements spec (from customer)","Alle Anforderungen stehen im Lastenheft.","All requirements are in the requirements specification."],
["Technik","die Abweichung, -en","deviation","Die Abweichung liegt außerhalb der Toleranz.","The deviation is outside the tolerance."],
["Technik","der Fehler, -","error, defect","Der Fehler wurde bei der Endkontrolle entdeckt.","The defect was discovered during final inspection."],
["Technik","die Maßnahme, -n","measure, action","Welche Maßnahmen schlagen Sie vor?","What measures do you suggest?"],
["Technik","die Wärmeübertragung","heat transfer","Bei der Wärmeübertragung spielt die Oberfläche eine große Rolle.","In heat transfer, the surface area plays a big role."],
["Alltag","die Anmeldung, -en","registration","Die Anmeldung beim Bürgeramt ist Pflicht.","Registration at the citizens' office is mandatory."],
["Alltag","die Aufenthaltserlaubnis, -se","residence permit","Meine Aufenthaltserlaubnis läuft im Oktober ab.","My residence permit expires in October."],
["Alltag","die Ausländerbehörde, -n","immigration office","Ich habe morgen einen Termin bei der Ausländerbehörde.","I have an appointment at the immigration office tomorrow."],
["Alltag","einen Termin vereinbaren","to make an appointment","Ich möchte gern einen Termin vereinbaren.","I would like to make an appointment."],
["Alltag","die Krankenversicherung, -en","health insurance","Die Krankenversicherung übernimmt die Kosten.","The health insurance covers the costs."],
["Alltag","die Überweisung, -en","bank transfer; referral","Die Überweisung kommt in zwei Tagen an.","The transfer arrives in two days."],
["Alltag","die Miete, -n","rent","Die Miete beträgt 450 Euro warm.","The rent is 450 euros including heating."],
["Alltag","die Nebenkosten (Pl.)","additional costs, utilities","Sind die Nebenkosten in der Miete enthalten?","Are the utilities included in the rent?"],
["Alltag","die Kaution, -en","deposit","Die Kaution bekomme ich beim Auszug zurück.","I get the deposit back when I move out."],
["Alltag","der Vermieter, -","landlord","Der Vermieter hat die Heizung reparieren lassen.","The landlord had the heating repaired."],
["Alltag","die Verspätung, -en","delay","Der Zug hat zehn Minuten Verspätung.","The train is ten minutes late."],
["Alltag","das Gleis, -e","platform, track","Der ICE fährt auf Gleis sieben ein.","The ICE is arriving at platform seven."],
["Alltag","die Kündigung, -en","termination (notice)","Die Kündigungsfrist beträgt drei Monate.","The notice period is three months."],
["Alltag","das Formular, -e","form","Bitte füllen Sie dieses Formular aus.","Please fill out this form."],
["Alltag","beantragen","to apply for (officially)","Ich möchte eine Verlängerung beantragen.","I would like to apply for an extension."],
["Alltag","die Bescheinigung, -en","certificate, confirmation","Ich brauche eine Bescheinigung von der Uni.","I need a certificate from the university."],
["Alltag","die Krankmeldung, -en","sick note","Ich schicke Ihnen die Krankmeldung per E-Mail.","I'll send you the sick note by email."],
["Alltag","der Beitrag, ¨e","fee, contribution","Der Semesterbeitrag muss bis Ende des Monats bezahlt werden.","The semester fee must be paid by the end of the month."]
];

/* GRAM: q = sentence with ___, o = options (first is correct), e = explanation */
const GRAM=[
{q:"Die Bauteile ___ in der Halle gefertigt.",o:["werden","wird","sind","haben"],e:"Passiv Präsens = werden + Partizip II. 'Bauteile' is plural → werden."},
{q:"Das Werkstück ___ gestern geprüft.",o:["wurde","wird","war","hat"],e:"Passiv Präteritum = wurde + Partizip II. Very common in reports."},
{q:"Der Bericht muss bis Freitag ___ werden.",o:["fertiggestellt","fertigstellen","fertigzustellen","fertigstellte"],e:"Passiv with modal verb: muss + Partizip II + werden."},
{q:"Wenn ich mehr Zeit ___, würde ich öfter üben.",o:["hätte","habe","hatte","hätten"],e:"Unreal condition → Konjunktiv II: ich hätte."},
{q:"___ Sie mir bitte die Zeichnung schicken?",o:["Könnten","Konnten","Kannten","Gekonnt"],e:"Konjunktiv II (könnten) makes requests polite. Essential at work."},
{q:"Das ist der Ingenieur, ___ das Projekt leitet.",o:["der","den","dem","dessen"],e:"The relative pronoun is the subject of 'leitet' → nominative masculine: der."},
{q:"Die Maschine, ___ wir gestern gekauft haben, ist sehr schnell.",o:["die","der","den","deren"],e:"Feminine + accusative object of 'gekauft' → die. Verb goes to the end of the relative clause."},
{q:"Das Unternehmen, bei ___ ich mich beworben habe, sitzt in München.",o:["dem","das","den","dessen"],e:"'bei' + Dativ; Unternehmen is neuter → bei dem."},
{q:"Ich lerne Deutsch, weil ich in Deutschland ___.",o:["arbeiten möchte","möchte arbeiten","arbeiten möchte ich","möchte ich arbeiten"],e:"After 'weil' the conjugated verb goes to the very end."},
{q:"Ich komme später, ___ der Zug Verspätung hat.",o:["weil","denn","deshalb","sondern"],e:"Verb at the end ('hat') → 'weil'. 'denn' would be followed by normal word order."},
{q:"Der Zug hat Verspätung, ___ komme ich später.",o:["deshalb","weil","obwohl","damit"],e:"'deshalb' takes position 1, so the verb follows directly: deshalb komme ich."},
{q:"___ ich Kopfschmerzen hatte, bin ich zur Arbeit gegangen.",o:["Obwohl","Weil","Damit","Deshalb"],e:"'obwohl' = although (contrast)."},
{q:"Ich schreibe eine E-Mail, ___ der Kunde die Informationen bekommt.",o:["damit","um","weil","dass"],e:"'damit' = so that, used when the subjects differ (ich / der Kunde)."},
{q:"Ich nutze die App, ___ mein Deutsch zu verbessern.",o:["um","damit","für","weil"],e:"Same subject (ich) → um … zu + Infinitiv."},
{q:"Ich interessiere mich ___ Regelungstechnik.",o:["für","an","über","auf"],e:"sich interessieren für + Akkusativ."},
{q:"Ich freue mich ___ das Vorstellungsgespräch.",o:["auf","über","für","an"],e:"sich freuen auf = look forward to (future). sich freuen über = be happy about (present/past)."},
{q:"Wir suchen einen ___ Ingenieur.",o:["erfahrenen","erfahrener","erfahrene","erfahrenes"],e:"Masculine accusative after 'einen' → ending -en."},
{q:"Sie hat ein sehr ___ Zeugnis.",o:["gutes","guter","gute","guten"],e:"Neuter accusative after 'ein' → ending -es."},
{q:"Die Dicke ___ Bleches beträgt zwei Millimeter.",o:["des","der","dem","das"],e:"Genitiv masculine/neuter: des + noun ending -(e)s."},
{q:"___ des hohen Drucks hat der Behälter gehalten.",o:["Trotz","Wegen","Während","Statt"],e:"trotz + Genitiv = despite. 'Wegen' (because of) doesn't fit logically."},
{q:"Die ___ des Bauteils dauert eine Stunde.",o:["Prüfung","Prüfen","Prüft","Geprüft"],e:"Nominalisierung: prüfen → die Prüfung. Technical German loves -ung nouns (always feminine)."},
{q:"Das gestern ___ Bauteil ist defekt.",o:["gelieferte","liefernde","lieferte","zu liefernde"],e:"Partizip II as adjective has passive meaning = 'das Bauteil, das gestern geliefert wurde'."},
{q:"An Ihrer Stelle ___ ich das Angebot annehmen.",o:["würde","werde","wurde","würden"],e:"Advice with Konjunktiv II: würde + Infinitiv."},
{q:"Ich weiß nicht, ___ er heute kommt.",o:["ob","dass","wenn","als"],e:"'ob' = whether (indirect yes/no question), verb at the end."},
{q:"___ ich in Indien gelebt habe, habe ich kein Deutsch gesprochen.",o:["Als","Wenn","Wann","Ob"],e:"'als' = one-time event/period in the past; 'wenn' = repeated or present/future."},
{q:"Ich muss ___ auf die Prüfung vorbereiten.",o:["mich","mir","sich","dich"],e:"sich vorbereiten auf; with 'ich' → mich."},
{q:"Ich warte auf die Antwort. – Ich warte ___.",o:["darauf","worauf","dafür","daran"],e:"da(r)-compound replaces 'auf + thing': darauf."},
{q:"Sehr geehrte Frau Schmidt, … Mit ___ Grüßen",o:["freundlichen","freundliche","freundlichem","freundlicher"],e:"Standard formal closing: 'Mit freundlichen Grüßen' (plural dative → -en)."},
{q:"Die Ergebnisse, ___ Richtigkeit niemand bezweifelt, wurden veröffentlicht.",o:["deren","dessen","die","denen"],e:"Genitive relative pronoun, plural → deren."},
{q:"Hätte ich das früher gewusst, ___ ich anders entschieden.",o:["hätte","wäre","würde","habe"],e:"Past unreal (Konjunktiv II Vergangenheit): hätte + Partizip II."}
];

const SPEAK=[
{t:"Introduce yourself (Vorstellungsgespräch)",sit:"The interviewer says: „Erzählen Sie etwas über sich.“ Introduce yourself: studies, interests, experience.",model:"Guten Tag, mein Name ist Max Mustermann. Ich komme aus Indien und studiere Maschinenbau im Master. Ich interessiere mich besonders für Konstruktion und Simulation. In meinem Studium habe ich mit CAD und FEM gearbeitet. Jetzt möchte ich meine Kenntnisse in der Praxis anwenden.",en:"Hello, my name is Max Mustermann. I'm from India and I'm doing a master's in mechanical engineering. I'm especially interested in design and simulation. During my studies I worked with CAD and FEM. Now I'd like to apply my knowledge in practice.",tips:["Ich komme aus … / Ich studiere …","Ich interessiere mich besonders für …","Ich habe mit … gearbeitet","meine Kenntnisse in der Praxis anwenden"]},
{t:"Why this company?",sit:"The interviewer asks: „Warum möchten Sie bei uns arbeiten?“",model:"Ich möchte bei Ihnen arbeiten, weil Ihr Unternehmen für innovative Produkte bekannt ist. Außerdem möchte ich praktische Erfahrung in der Entwicklung sammeln und von erfahrenen Kollegen lernen.",en:"I'd like to work for you because your company is known for innovative products. I also want to gain practical experience in development and learn from experienced colleagues.",tips:["bekannt sein für …","praktische Erfahrung sammeln","von Kollegen lernen","Außerdem …"]},
{t:"Your German level (honest and positive)",sit:"They ask: „Wie gut ist Ihr Deutsch?“ Be honest, but show you're improving.",model:"Mein Deutsch ist ungefähr auf B1-Niveau, aber ich lerne jeden Tag und verbessere mich schnell. Fachtexte kann ich schon gut lesen. Im Gespräch brauche ich manchmal etwas mehr Zeit, aber ich verstehe das Wichtigste.",en:"My German is around B1 level, but I study every day and I'm improving quickly. I can already read technical texts well. In conversation I sometimes need a bit more time, but I understand the main points.",tips:["auf B1-Niveau","sich verbessern","Fachtexte lesen","das Wichtigste verstehen"]},
{t:"Ask someone to repeat (meeting)",sit:"In a team meeting you missed the last sentence. Politely ask to repeat it.",model:"Entschuldigung, könnten Sie das bitte wiederholen? Ich habe den letzten Teil nicht ganz verstanden. Könnten Sie etwas langsamer sprechen?",en:"Excuse me, could you please repeat that? I didn't quite understand the last part. Could you speak a little more slowly?",tips:["Könnten Sie das wiederholen?","nicht ganz verstanden","etwas langsamer"]},
{t:"Daily stand-up (status update)",sit:"Report to your team: what you did yesterday, what you do today, and one problem.",model:"Gestern habe ich das CAD-Modell fertiggestellt. Heute führe ich die Simulation durch. Im Moment gibt es ein Problem mit dem Netz, aber ich arbeite daran und melde mich, wenn ich die Ergebnisse habe.",en:"Yesterday I finished the CAD model. Today I'm running the simulation. At the moment there's a problem with the mesh, but I'm working on it and will get back to you when I have the results.",tips:["Gestern habe ich … + Partizip II","Heute führe ich … durch","Es gibt ein Problem mit …","Ich arbeite daran"]},
{t:"Ausländerbehörde appointment",sit:"You're at the immigration office with an appointment. Explain why you came.",model:"Guten Tag, ich habe um zehn Uhr einen Termin. Ich möchte meine Aufenthaltserlaubnis verlängern. Hier sind meine Unterlagen: der Pass, die Immatrikulationsbescheinigung und der Nachweis der Krankenversicherung.",en:"Hello, I have an appointment at ten o'clock. I'd like to extend my residence permit. Here are my documents: my passport, my enrolment certificate and proof of health insurance.",tips:["Ich habe einen Termin um …","verlängern","die Unterlagen","der Nachweis"]},
{t:"Ask a colleague for help",sit:"You don't understand a tolerance on a drawing. Ask a colleague (informal 'du').",model:"Hast du kurz Zeit? Ich habe eine Frage zu dieser Zeichnung. Ich bin mir nicht sicher, welche Toleranz hier gilt. Kannst du mir das bitte erklären?",en:"Do you have a moment? I have a question about this drawing. I'm not sure which tolerance applies here. Could you explain it to me, please?",tips:["Hast du kurz Zeit?","eine Frage zu …","Ich bin mir nicht sicher, …","Kannst du mir das erklären?"]},
{t:"Describe a technical component",sit:"Explain how a shaft in a gearbox works (use Passiv).",model:"Die Welle wird durch zwei Lager gehalten. Sie überträgt das Drehmoment vom Motor auf das Zahnrad. Die Lager werden regelmäßig geschmiert, damit die Reibung gering bleibt.",en:"The shaft is held by two bearings. It transmits the torque from the motor to the gear. The bearings are lubricated regularly so that friction stays low.",tips:["wird … gehalten (Passiv)","überträgt … auf …","damit die Reibung gering bleibt"]},
{t:"Problem with the flat (Vermieter)",sit:"Call your landlord: the heating has not worked since yesterday.",model:"Guten Tag, hier spricht Max Mustermann aus der Wohnung drei. Die Heizung funktioniert seit gestern nicht mehr. Könnten Sie bitte jemanden vorbeischicken? Ich bin ab achtzehn Uhr zu Hause.",en:"Hello, this is Max Mustermann from flat three. The heating hasn't worked since yesterday. Could you please send someone over? I'll be home from 6 pm.",tips:["seit gestern nicht mehr","Könnten Sie bitte …","vorbeischicken","ab 18 Uhr zu Hause"]},
{t:"Phone call about a Werkstudent job",sit:"You call a company about a job advert and want to speak to the right person.",model:"Guten Tag, mein Name ist Max Mustermann. Ich rufe wegen der ausgeschriebenen Werkstudentenstelle an. Könnte ich bitte mit der zuständigen Person sprechen? Ich hätte außerdem eine Frage zu den Arbeitszeiten.",en:"Hello, my name is Max Mustermann. I'm calling about the advertised working-student position. Could I please speak to the person responsible? I'd also have a question about the working hours.",tips:["Ich rufe wegen … an","die ausgeschriebene Stelle","die zuständige Person","Ich hätte eine Frage zu …"]}
];

const PLACE=[
{l:"A2",q:"Gestern ___ ich ins Kino gegangen.",o:["bin","habe","hat","werde"]},
{l:"A2",q:"Ich helfe ___ Freund bei den Hausaufgaben.",o:["meinem","meinen","mein","meiner"]},
{l:"A2",q:"Ich fahre jeden Tag mit ___ Bus zur Uni.",o:["dem","den","der","das"]},
{l:"A2",q:"Ich möchte morgen ___ Arzt gehen.",o:["zum","zur","zu","in"]},
{l:"B1",q:"Ich weiß nicht, ob er heute ___.",o:["kommt","kommt er","kommen","kam er"]},
{l:"B1",q:"Wenn ich Zeit ___, würde ich mehr reisen.",o:["hätte","habe","hatte","hat"]},
{l:"B1",q:"Das ist das Haus, in ___ ich vor zehn Jahren gewohnt habe.",o:["dem","das","den","dessen"]},
{l:"B1",q:"Ich ärgere mich ___ den Lärm.",o:["über","für","auf","an"]},
{l:"B1",q:"Das Auto ___ gerade repariert.",o:["wird","werden","hat","wurden"]},
{l:"B2",q:"Obwohl er viel gelernt hat, ___.",o:["hat er die Prüfung nicht bestanden","er hat die Prüfung nicht bestanden","die Prüfung nicht bestanden hat er","hat die Prüfung er nicht bestanden"]},
{l:"B2",q:"Der Antrag muss bis Montag ___ werden.",o:["eingereicht","einreichen","einzureichen","einreicht"]},
{l:"B2",q:"Er tat so, als ___ er alles verstanden.",o:["hätte","hat","hatte","haben"]},
{l:"B2",q:"Aufgrund ___ Lieferproblems verzögert sich das Projekt.",o:["des","dem","der","das"]},
{l:"B2",q:"Das von der Firma ___ Produkt ist sehr erfolgreich.",o:["entwickelte","entwickelnde","entwickelt","zu entwickelnde"]},
{l:"B2",q:"Die Firma, ___ Produkte weltweit verkauft werden, sitzt in Ulm.",o:["deren","dessen","die","der"]},
{l:"C1",q:"Hätte ich das früher gewusst, ___ ich anders entschieden.",o:["hätte","wäre","würde","habe"]},
{l:"C1",q:"Das Projekt ist ___ gescheitert, dass die Kosten explodiert sind.",o:["daran","dadurch","dafür","darauf"]}
];
